### ISSUE TITLE
No Exports Found

### ISSUE THREAD

**Issue by ZockerBoysHD** [mythicrp/mythic_progbar#4]
**Describe the bug**
If i install the script and try to trigger the export either Server or Client side it doesn't work at all

**To Reproduce**
Install newest script version and then just trigger the export

**Expected behavior**
a working progressbar

**Screenshots**
https://screens.egopvp.com/images/2019/10/24/FiveM_GTAProcess_YF4WDOQ4ga.png

**Comment by Alzar** [comment]
Closing this as exports are registered as needed and it'd be something external to this causing issues, if you can provide any more info on it breaking or repro steps I'll reopen & address
